# .cnb.yml
1.0.*:
  tag_push:
    - env:
        # - KO_DEFAULTBASEIMAGE=ccr.ccs.tencentyun.com/afan-public/ubuntu:24.04-offlineui
        # - KO_DOCKER_REPO=ccr.ccs.tencentyun.com/afan-public/kbcli-helper
        # export KO_DEFAULTBASEIMAGE=ccr.ccs.tencentyun.com/afan-public/ubuntu:24.04-offlineui && export KO_DOCKER_REPO=ccr.ccs.tencentyun.com/afan-public/w7panel 
      docker:
        # 通过此参数控制使用的 Dockerfile 构建镜像必须公开
        image: ccr.ccs.tencentyun.com/afan-public/ubuntu:go-build
        volumes: 
          - /home/workspace/.cache:read-write
          - /root/.cache:read-write  
      stages:
       
        - name: login
          script: /root/go/bin/ko login docker.cnb.cool -u cnb -p ${CNB_TOKEN}
        - name: build
          script:  export KO_DOCKER_REPO=docker.cnb.cool/i0358/kbcli-helper && export KO_DEFAULTBASEIMAGE=ccr.ccs.tencentyun.com/afan-public/ubuntu:24.04-offlineui && /root/go/bin/ko build --bare --tags=${CNB_BRANCH} --tag-only --sbom=none --platform=all

$:
  vscode:
    - runner:
        cpus: 8
      docker:
        image: docker.cnb.cool/i0358/kbcli-helper:ide
      services:
        - vscode
        - docker
      stages:
        - name: ls
          script: ls -al
